# Generated by Django 6.0 on 2026-06-07 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("bd_models", "0015_alter_ballinstance_server_id_and_more")]

    operations = [
        migrations.CreateModel(
            name="CraftRecipe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "enabled",
                    models.BooleanField(default=True, help_text="Whether this recipe can currently be crafted"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "input_ball_1",
                    models.ForeignKey(
                        help_text="One of the two countryballs required to craft the result",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="craft_recipes_as_input_1",
                        to="bd_models.ball",
                    ),
                ),
                (
                    "input_ball_2",
                    models.ForeignKey(
                        help_text="The other countryball required to craft the result",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="craft_recipes_as_input_2",
                        to="bd_models.ball",
                    ),
                ),
                (
                    "result_ball",
                    models.ForeignKey(
                        help_text="The countryball obtained by crafting the two inputs together",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="craft_recipes_as_result",
                        to="bd_models.ball",
                    ),
                ),
                (
                    "special",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional special applied to the crafted countryball",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="craft_recipes",
                        to="bd_models.special",
                    ),
                ),
            ],
            options={"db_table": "craftrecipe", "managed": True},
        )
    ]
