# Generated by Django 6.0 on 2026-06-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("crafting", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="craftrecipe",
            name="inherit_special",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Only usable when no special is set above. If enabled, the crafted countryball "
                    "randomly keeps one of the two inputs' specials (e.g. crafting a shiny with a "
                    "non-shiny has a 50/50 chance of producing a shiny). If disabled, the result "
                    "never has a special."
                ),
            ),
        )
    ]
